In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('districts_info.csv')

In [3]:
#removing NaN values
df = df.dropna()
df

,district_id,state,locale,pct_black/hispanic,pct_free/reduced,county_connections_ratio,pp_total_raw
0,8815,Illinois,Suburb,"[0, 0.2[","[0, 0.2[","[0.18, 1[","[14000, 16000["
2,4921,Utah,Suburb,"[0, 0.2[","[0.2, 0.4[","[0.18, 1[","[6000, 8000["
5,5987,Wisconsin,Suburb,"[0, 0.2[","[0, 0.2[","[0.18, 1[","[10000, 12000["
6,3710,Utah,Suburb,"[0, 0.2[","[0.4, 0.6[","[0.18, 1[","[6000, 8000["
7,7177,North Carolina,Suburb,"[0.2, 0.4[","[0.2, 0.4[","[0.18, 1[","[8000, 10000["
...,...,...,...,...,...,...,...
220,3732,Michigan,Suburb,"[0.4, 0.6[","[0.4, 0.6[","[0.18, 1[","[12000, 14000["
224,3266,Utah,Town,"[0, 0.2[","[0.4, 0.6[","[0.18, 1[","[10000, 12000["
227,1705,Washington,City,"[0.2, 0.4[","[0.4, 0.6[","[0.18, 1[","[12000, 14000["
228,9515,New York,Rural,"[0, 0.2[","[0.4, 0.6[","[0.18, 1[","[18000, 20000["
230,4929,Virginia,Rural,"[0, 0.2[","[0.4, 0.6[","[0.18, 1[","[12000, 14000["

In [5]:
#ordering by state
pd.set_option('display.max_rows', None)
df.sort_values('state')

,district_id,state,locale,pct_black/hispanic,pct_free/reduced,county_connections_ratio,pp_total_raw
104,6919,Florida,Suburb,"[0.4, 0.6[","[0.4, 0.6[","[0.18, 1[","[6000, 8000["
0,8815,Illinois,Suburb,"[0, 0.2[","[0, 0.2[","[0.18, 1[","[14000, 16000["
169,2285,Illinois,Suburb,"[0, 0.2[","[0.4, 0.6[","[0.18, 1[","[12000, 14000["
56,9899,Illinois,Suburb,"[0.2, 0.4[","[0, 0.2[","[0.18, 1[","[12000, 14000["
58,4629,Illinois,Suburb,"[0, 0.2[","[0.2, 0.4[","[0.18, 1[","[16000, 18000["
34,6577,Illinois,Suburb,"[0, 0.2[","[0, 0.2[","[0.18, 1[","[10000, 12000["
71,1712,Illinois,Suburb,"[0.4, 0.6[","[0.4, 0.6[","[0.18, 1[","[12000, 14000["
78,5042,Illinois,Town,"[0.2, 0.4[","[0.8, 1[","[0.18, 1[","[10000, 12000["
24,9043,Illinois,Suburb,"[0.8, 1[","[0.8, 1[","[0.18, 1[","[12000, 14000["
54,2601,Illinois,Suburb,"[0.6, 0.8[","[0.4, 0.6[","[0.18, 1[","[12000, 14000["
20,2779,Illinois,Rural,"[0, 0.2[","[0, 0.2[","[0.18, 1[","[10000, 12000["
90,5890,Illinois,Suburb,"[0.2, 0.4[","[0.2, 0.4[","[0.18, 1[","[18000, 20000["
147,1052,Illinois,Suburb,"[0.2, 0.4[","[0.2, 0.4[","[0.18, 1[","[16000, 18000["
114,9553,Illinois,Suburb,"[0, 0.2[","[0, 0.2[","[0.18, 1[","[14000, 16000["
116,8937,Illinois,Rural,"[0, 0.2[","[0, 0.2[","[0.18, 1[","[12000, 14000["
135,3248,Illinois,Suburb,"[0.6, 0.8[","[0.6, 0.8[","[0.18, 1[","[12000, 14000["
132,2393,Illinois,Suburb,"[0, 0.2[","[0, 0.2[","[0.18, 1[","[12000, 14000["
18,1877,Illinois,Rural,"[0, 0.2[","[0, 0.2[","[0.18, 1[","[12000, 14000["
50,8784,Illinois,Suburb,"[0.6, 0.8[","[0.6, 0.8[","[0.18, 1[","[10000, 12000["
152,2870,Indiana,Suburb,"[0.8, 1[","[0.6, 0.8[","[0.18, 1[","[8000, 10000["
139,5627,Indiana,Rural,"[0, 0.2[","[0.4, 0.6[","[0.18, 1[","[8000, 10000["
65,3222,Indiana,City,"[0.2, 0.4[","[0.6, 0.8[","[0.18, 1[","[8000, 10000["
115,1536,Indiana,Rural,"[0, 0.2[","[0.4, 0.6[","[0.18, 1[","[8000, 10000["
130,1324,Indiana,Rural,"[0, 0.2[","[0.4, 0.6[","[0.18, 1[","[8000, 10000["
16,4808,Indiana,City,"[0.8, 1[","[0.8, 1[","[0.18, 1[","[8000, 10000["
196,3228,Indiana,Town,"[0, 0.2[","[0.4, 0.6[","[0.18, 1[","[8000, 10000["
220,3732,Michigan,Suburb,"[0.4, 0.6[","[0.4, 0.6[","[0.18, 1[","[12000, 14000["
214,6144,Michigan,Suburb,"[0.4, 0.6[","[0.6, 0.8[","[0.18, 1[","[10000, 12000["
52,3550,Minnesota,Suburb,"[0.4, 0.6[","[0.6, 0.8[","[0.18, 1[","[14000, 16000["
113,2956,Missouri,City,"[0, 0.2[","[0.4, 0.6[","[0.18, 1[","[8000, 10000["
144,4348,Missouri,Suburb,"[0, 0.2[","[0.2, 0.4[","[0.18, 1[","[8000, 10000["
197,5422,Missouri,Town,"[0, 0.2[","[0.2, 0.4[","[0.18, 1[","[8000, 10000["
27,4051,Missouri,Suburb,"[0, 0.2[","[0.2, 0.4[","[0.18, 1[","[10000, 12000["
57,1742,Missouri,Suburb,"[0, 0.2[","[0.2, 0.4[","[0.18, 1[","[8000, 10000["
201,8256,New Jersey,Suburb,"[0, 0.2[","[0, 0.2[","[0.18, 1[","[14000, 16000["
44,8433,New Jersey,Suburb,"[0, 0.2[","[0, 0.2[","[0.18, 1[","[18000, 20000["
128,1470,New York,Rural,"[0, 0.2[","[0.4, 0.6[","[0.18, 1[","[32000, 34000["
124,4775,New York,Suburb,"[0, 0.2[","[0.2, 0.4[","[0.18, 1[","[16000, 18000["
51,7798,New York,Rural,"[0, 0.2[","[0.2, 0.4[","[0.18, 1[","[22000, 24000["
228,9515,New York,Rural,"[0, 0.2[","[0.4, 0.6[","[0.18, 1[","[18000, 20000["
121,8520,New York,Rural,"[0, 0.2[","[0.2, 0.4[","[0.18, 1[","[16000, 18000["
154,3558,North Carolina,Suburb,"[0.2, 0.4[","[0.2, 0.4[","[0.18, 1[","[8000, 10000["
84,7767,North Carolina,City,"[0.4, 0.6[","[0.6, 0.8[","[0.18, 1[","[10000, 12000["
9,6584,North Carolina,Rural,"[0.4, 0.6[","[0.6, 0.8[","[0.18, 1[","[8000, 10000["
7,7177,North Carolina,Suburb,"[0.2, 0.4[","[0.2, 0.4[","[0.18, 1[","[8000, 10000["
80,4683,Texas,Suburb,"[0.4, 0.6[","[0.4, 0.6[","[0.18, 1[","[8000, 10000["
69,8884,Texas,City,"[0.6, 0.8[","[0.4, 0.6[","[0.18, 1[","[8000, 10000["
224,3266,Utah,Town,"[0, 0.2[","[0.4, 0.6[","[0.18, 1[","[10000, 12000["
134,9230,Utah,Rural,"[0, 0.2[","[0, 0.2[","[0.18, 1[","[6000, 8000["
178,4744,Utah,Suburb,"[0.2, 0.4[","[0.2, 0.4[","[0.18, 1[","[8000, 10000["
163,4668,Utah,Suburb,"[0, 0.2[","[0.2, 0.4[","[0.18, 1[","[6000, 8000["
180,7541,Utah,Suburb,"[0.2, 0.4[","[0.2, 0.4[","[0.18, 1[","[8000, 10000["
206,4373,Utah,City,"[0, 0.2[","[0, 0.2[","[0.18, 1[","[8000, 10000["
183,1270,Utah,Rural,"[0, 0.2[","[0.4, 0.6[","[0.18, 1[","[8000, 10000["
151,1204,Utah,Suburb,"[0, 0.2[","[0, 0.2[","[0.18, 1[","[6000, 8000["
191,4183,Utah,Town,"[0, 0.2[","[0.4, 0.6[","[0.18, 1[","[8000, 10000["
213,2441,Utah,Town,"[0, 0.2[","[0.2, 0.4[","[0.18, 1[","[8000, 10000["
148,6762,Utah,Suburb,"[0, 0.2[","[0, 0.2[","[0.18, 1[","[4000, 6000["
98,5600,Utah,Suburb,"[0, 0.2[","[0.2, 0.4[","[0.18, 1[","[6000, 8000["
126,9778,Utah,Town,"[0, 0.2[","[0.4, 0.6[","[0.18, 1[","[8000, 10000["
2,4921,Utah,Suburb,"[0, 0.2[","[0.2, 0.4[","[0.18, 1[","[6000, 8000["
6,3710,Utah,Suburb,"[0, 0.2[","[0.4, 0.6[","[0.18, 1[","[6000, 8000["
8,9812,Utah,Suburb,"[0, 0.2[","[0.2, 0.4[","[0.18, 1[","[6000, 8000["
15,7614,Utah,City,"[0.2, 0.4[","[0.2, 0.4[","[0.18, 1[","[8000, 10000["
21,8328,Utah,Town,"[0, 0.2[","[0.4, 0.6[","[0.18, 1[","[10000, 12000["
36,4936,Utah,Suburb,"[0, 0.2[","[0, 0.2[","[0.18, 1[","[6000, 8000["
131,3160,Utah,Suburb,"[0, 0.2[","[0.2, 0.4[","[0.18, 1[","[8000, 10000["
45,2165,Utah,Suburb,"[0.2, 0.4[","[0.2, 0.4[","[0.18, 1[","[6000, 8000["
55,7660,Utah,Suburb,"[0, 0.2[","[0, 0.2[","[0.18, 1[","[6000, 8000["
66,1772,Utah,City,"[0.2, 0.4[","[0.4, 0.6[","[0.18, 1[","[8000, 10000["
41,5231,Utah,Town,"[0, 0.2[","[0.4, 0.6[","[0.18, 1[","[10000, 12000["
85,7308,Utah,Suburb,"[0, 0.2[","[0.2, 0.4[","[0.18, 1[","[4000, 6000["
95,3864,Utah,Suburb,"[0, 0.2[","[0, 0.2[","[0.18, 1[","[6000, 8000["
123,3772,Utah,Suburb,"[0, 0.2[","[0.2, 0.4[","[0.18, 1[","[8000, 10000["
79,3692,Utah,Suburb,"[0, 0.2[","[0.4, 0.6[","[0.18, 1[","[8000, 10000["
109,7387,Utah,City,"[0, 0.2[","[0.2, 0.4[","[0.18, 1[","[6000, 8000["
230,4929,Virginia,Rural,"[0, 0.2[","[0.4, 0.6[","[0.18, 1[","[12000, 14000["
26,1549,Virginia,Suburb,"[0, 0.2[","[0.2, 0.4[","[0.18, 1[","[10000, 12000["
105,7980,Virginia,Rural,"[0, 0.2[","[0.4, 0.6[","[0.18, 1[","[10000, 12000["
227,1705,Washington,City,"[0.2, 0.4[","[0.4, 0.6[","[0.18, 1[","[12000, 14000["
122,2130,Washington,Suburb,"[0.4, 0.6[","[0.6, 0.8[","[0.18, 1[","[14000, 16000["
82,2567,Washington,Suburb,"[0, 0.2[","[0.2, 0.4[","[0.18, 1[","[12000, 14000["
194,5510,Washington,City,"[0.2, 0.4[","[0.4, 0.6[","[0.18, 1[","[14000, 16000["
33,2167,Washington,Suburb,"[0, 0.2[","[0, 0.2[","[0.18, 1[","[14000, 16000["
11,7457,Washington,City,"[0.4, 0.6[","[0.4, 0.6[","[0.18, 1[","[12000, 14000["
5,5987,Wisconsin,Suburb,"[0, 0.2[","[0, 0.2[","[0.18, 1[","[10000, 12000["
89,8902,Wisconsin,Suburb,"[0, 0.2[","[0.2, 0.4[","[0.18, 1[","[10000, 12000["
141,7752,Wisconsin,Suburb,"[0, 0.2[","[0, 0.2[","[0.18, 1[","[10000, 12000["

In [6]:
#how many districts for each state
df.groupby('state').state.count()

state
Florida            1
Illinois          18
Indiana            7
Michigan           2
Minnesota          1
Missouri           5
New Jersey         2
New York           5
North Carolina     4
Texas              2
Utah              29
Virginia           3
Washington         6
Wisconsin          3
Name: state, dtype: int64